# Generated by Django 4.2.7 on 2023-11-07 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table='MUSICIAN',
        ),
    ]
