# Generated by Django 4.2.7 on 2023-11-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_musician_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='musician',
            table=None,
        ),
    ]
