# Generated by Django 4.2.7 on 2023-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_musician_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
